config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :users
  
  resources :songs do
  resources :reviews, except: [:show, :index]

  end

  root 'songs#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :user
	has_many :reviews
	mount_uploader :cover, CoverUploader
	mount_uploader :audio, AudioUploader
	acts_as_taggable_on :tags
	acts_as_punchable

def embed(video_embed)
    youtube_id = video_embed.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        

         has_many :songs
         has_many :reviews, dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :email, :avatar, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end

  # protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_song
  before_action :authenticate_user!

    def new
    @review = Review.new
    
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.song_id = @song.id

    if @review.save
      redirect_to @song

    else

      render 'new'
    end
    
  end

  def update
    @review.update(review_params)
    
  end

  def destroy
    @review.destroy
    redirect_to root_path
    
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_song
      @song = Song.find(params[:song_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy,]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /songs
  # GET /songs.json
  def index
      @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
      @reviews = Review.where(song_id: @song.id).order("created_at DESC")
      @song.punch(request)
      
      if @reviews.blank?
          @avg_review = 0
      else
          @avg_review = @reviews.average(:rating).round(2)
      end
  end
  

  # GET /songs/new
  def new
      @song = current_user.songs.build
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = current_user.songs.build(song_params)
    @song.user_id = current_user.id

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :description, :audio, :cover, :genre, :song_type, :artist, :country, :video_embed, :lyrics, :release_date, :name, :tag_list)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  @user = current_user.users.build
end

  def edit
  end


 private
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:avatar, :email)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footerplayer2.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body{ background:#789;}
div#audio_player{ width:450px; float:right; height:60px; background: url(images/player/skin1.png) no-repeat; border-radius:4px;}
div#audio_controls{ margin-left:66px; }
div#audio_controls > button{ border:none; cursor:pointer; outline:none; display:block; float:left; margin:22px 10px 0px 0px; }
div#audio_controls > input{ outline:none; display:block; float:left; margin:24px 10px 0px 0px; }
button#playpausebtn{
	background:url(images/player/pause.png) no-repeat;
	width:25px;
	height:25px;
}
button#mutebtn{
	background:url(images/player/speaker.png) no-repeat;
	width:5px;
	height:14px;
}
input#seekslider{
	width:100px;
}
input#volumeslider{
	width: 70px;
}
div#timebox{
	margin: 23px 10px 0px 0px;
	float:left;
	width:80px;
	background:#000;
	border-bottom:#333 1px solid;
	text-align:center;
	color: #09F; 
	font-family: Arial, Helvetica, sans-serif;
	font-size:11px;
}
input[type='range'] {
    -webkit-appearance: none !important;
	margin:0px;
	padding:0px;
    background: #000;
    height:13px;
	border-bottom:#333 1px solid;
}
input[type='range']::-ms-fill-lower  {
	background:#000;
}
input[type='range']::-ms-fill-upper  {
	background:#000;
}
input[type='range']::-moz-range-track {
	border:none;
    background: #000;
}
input[type='range']::-webkit-slider-thumb {
    -webkit-appearance: none !important;
    background: radial-gradient(#FFF, #333);
    height:11px;
    width:11px;
	border-radius:100%;
	cursor:pointer;
}
input[type='range']::-moz-range-thumb {
    background: radial-gradient(#FFF, #333);
    height:11px;
    width:11px;
	border-radius:100%;
	cursor:pointer;
}
input[type='range']::-ms-thumb {
    -webkit-appearance: none !important;
    background: radial-gradient(#FFF, #333);
    height:11px;
    width:11px;
	border-radius:100%;
	cursor:pointer;
}
</style>
<script>
var audio, playbtn, mutebtn, seekslider, volumeslider, seeking=false, seekto, curtimetext, durtimetext;

<!--compactibility-->


function initAudioPlayer(){
	audio = new Audio();
	audio.src = "images/player/Stoker.mp3";
	audio.loop = true;
	audio.play();
	// Set object references
	playbtn = document.getElementById("playpausebtn");
	mutebtn = document.getElementById("mutebtn");
	seekslider = document.getElementById("seekslider");
	volumeslider = document.getElementById("volumeslider");
	curtimetext = document.getElementById("curtimetext");
	durtimetext = document.getElementById("durtimetext");
	// Add Event Handling
	playbtn.addEventListener("click",playPause);
	mutebtn.addEventListener("click", mute);
	seekslider.addEventListener("mousedown", function(event){ seeking=true; seek(event); });
	seekslider.addEventListener("mousemove", function(event){ seek(event); });
	seekslider.addEventListener("mouseup",function(){ seeking=false; });
	volumeslider.addEventListener("mousemove", setvolume);
	audio.addEventListener("timeupdate", function(){ seektimeupdate(); });
	// Functions
	function playPause(){
		if(audio.paused){
		    audio.play();
		    playbtn.style.background = "url(images/player/pause.png) no-repeat";
	    } else {
		    audio.pause();
		    playbtn.style.background = "url(images/player/play.png) no-repeat";
	    }
	}
	function mute(){
		if(audio.muted){
		    audio.muted = false;
		    mutebtn.style.background = "url(images/player/speaker.png) no-repeat";
	    } else {
		    audio.muted = true;
		    mutebtn.style.background = "url(images/speaker_muted.png) no-repeat";
	    }
	}
	function seek(event){
	    if(seeking){
		    seekslider.value = event.clientX - seekslider.offsetLeft;
	        seekto = audio.duration * (seekslider.value / 100);
	        audio.currentTime = seekto;
	    }
    }
	function setvolume(){
	    audio.volume = volumeslider.value / 100;
    }
	function seektimeupdate(){
		var nt = audio.currentTime * (100 / audio.duration);
		seekslider.value = nt;
		var curmins = Math.floor(audio.currentTime / 60);
	    var cursecs = Math.floor(audio.currentTime - curmins * 60);
	    var durmins = Math.floor(audio.duration / 60);
	    var dursecs = Math.floor(audio.duration - durmins * 60);
		if(cursecs < 10){ cursecs = "0"+cursecs; }
	    if(dursecs < 10){ dursecs = "0"+dursecs; }
	    if(curmins < 10){ curmins = "0"+curmins; }
	    if(durmins < 10){ durmins = "0"+durmins; }
		curtimetext.innerHTML = curmins+":"+cursecs;
	    durtimetext.innerHTML = durmins+":"+dursecs;
	}
}
window.addEventListener("load", initAudioPlayer);
</script>
</head>
<body>
<div id="audio_player">
  <div id="audio_controls">
    <button id="playpausebtn"></button>
    <input id="seekslider" type="range" min="0" max="100" value="0" step="1">
    <div id="timebox">
      <span id="curtimetext">00:00</span> / <span id="durtimetext">00:00</span>
    </div>
    <button id="mutebtn"></button>
    <input id="volumeslider" type="range" min="0" max="100" value="100" step="1">
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Base</title>
  <%= stylesheet_link_tag "application", params[:controller], :media => "all" %>
<%= javascript_include_tag "application", params[:controller], :media => "all" %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'baseplayer', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  


  <%= csrf_meta_tags %>

  
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="whitenav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "African Music Base", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Song", new_song_path, class: "active" %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to 'Profile', current_user %> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>


<!---<div class="pull-right">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search African Music Base" name="srch-term" id="srch-term" size="34px">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>--->
      
    </div><!-- /.navbar-collapse -->




    <!-- Collect the nav links, forms, and other content for toggling -->
   



  </div><!-- /.container-fluid -->
</nav>

<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>



    
<%= yield %>


</div>



</body>

<footer>

  

  </div> 


</footer>


   
</html>

app/views/reviews/_form.html.erb
<%= form_for([@song, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/dindex.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/dshow.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<<%= link_to 'Back', song_path(@song) %

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', song_path(@song) %>

app/views/songs/_amazing.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <meta name="viewport" content="width=device-width">
    <title>Amazing HTML5 Audio Player, powered by http://amazingaudioplayer.com</title>
    
    <!-- Insert to your webpage before the </head> -->

    
    <script src="audioplayerengine/jquery.js"></script>
    <script src="audioplayerengine/amazingaudioplayer.js"></script>
    <link rel="stylesheet" type="text/css" href="audioplayerengine/initaudioplayer-1.css">
    <script src="audioplayerengine/initaudioplayer-1.js"></script>
    <!-- End of head section HTML codes -->
    
</head>
<body>
<div style="margin:12px auto;">
    
    <!-- Insert to your webpage where you want to display the audio player -->
    <div id="amazingaudioplayer-1" style="display:block;position:relative;width:300px;height:auto;margin:0px auto 0px;">
        <ul class="amazingaudioplayer-audios" style="display:none;">
            <li data-artist="" data-title="" data-album="" data-info="" data-image="" data-duration="0">
                <% @songs.each do |song| %>

                <div class="amazingaudioplayer-source" data-src="<%= song.audio.url %>" data-type="audio/mpeg" />
            </li>
            <li data-artist="" data-title="" data-album="" data-info="" data-image="" data-duration="0">
                <div class="amazingaudioplayer-source" data-src="<%= song.audio.url %>" data-type="audio/mpeg" />
            </li>
        </ul>
        <div class="amazingaudioplayer-engine"><a href="http://amazingaudioplayer.com" title="html5 mp3 player">jquery mp3 player</a></div>
    </div>

    <% end %>
    <!-- End of body section HTML codes -->

</div>
</body>
</html>

app/views/songs/_baseplayer.html.erb
 
<script>

var audio;

//Hide Pause Initially
$('#pause').hide();
$('#playlist').hide();
  
//Initializer - Play First Song
initAudio($('#playlist li'));
  
function initAudio(element){
  var song = element.attr('song');
    var title = element.text();
    var cover = element.attr('cover');
    var artist = element.attr('artist');

  //Create a New Audio Object
  audio = new Audio(song);
  
  if(!audio.currentTime){
    $('#duration').html('0.00');
  }

  $('#audio-player .title').text(title);
    $('#audio-player .artist').text(artist);
  
  //Insert Cover Image
  $('img.cover').attr('src','images/covers/' + cover);
  
  $('#playlist li').removeClass('active');
    element.addClass('active');
}


//Play Button
$('#play').click(function(){
  audio.play();
  $('#play').hide();
  $('#pause').show();
  $('#duration').fadeIn(400);
  showDuration();
});

//Pause Button
$('#pause').click(function(){
  audio.pause();
  $('#pause').hide();
  $('#play').show();
});
  
//Stop Button
$('#stop').click(function(){
  audio.pause();    
  audio.currentTime = 0;
  $('#pause').hide();
  $('#play').show();
  $('#duration').fadeOut(400);
});

//Next Button
$('#next').click(function(){
    audio.pause();
    var next = $('#playlist li.active').next();
    if (next.length == 0) {
        next = $('#playlist li:first-child');
    }
    initAudio(next);
  audio.play();
  showDuration();
});

//Prev Button
$('#prev').click(function(){
    audio.pause();
    var prev = $('#playlist li.active').prev();
    if (prev.length == 0) {
        prev = $('#playlist li:last-child');
    }
    initAudio(prev);
  audio.play();
  showDuration();
});

//Playlist Song Click

$('#playlist').click(function () {
    audio.pause();
    initAudio($(this));
  $('#play').hide();
  $('#pause').show();
  $('#duration').fadeIn(400);
  audio.play();
  showDuration();
}); 

//Volume Control
$('#volume').change(function(){
  audio.volume = parseFloat(this.value / 10);
});
  
//Time Duration
function showDuration(){
  $(audio).bind('timeupdate', function(){
    //Get hours and minutes
    var s = parseInt(audio.currentTime % 60);
    var m = parseInt((audio.currentTime / 60) % 60);
    //Add 0 if seconds less than 10
    if (s < 10) {
      s = '0' + s;
    }
    $('#duration').html(m + '.' + s); 
    var value = 0;
    if (audio.currentTime > 0) {
      value = Math.floor((100 / audio.duration) * audio.currentTime);
    }
    $('#progress').css('width',value+'%');
  });
}


</script>

app/views/songs/_lyrics.html.erb
<%= @song.lyrics %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index2.html.erb
<!DOCTYPE html>
<html>
<head>
<title>African Music Base</title>
<!--audio css-->

<style type="text/css">


button{ border:none; cursor:pointer; outline:none; }
button#playpausebtn{
  background:url(images/play.png) no-repeat;
  width:58px;
  height:56px;
}
button#mutebtn{
  background:url(images/speaker.png) no-repeat;
  width:5px;
  height:14px;
}

<!-- analyzer -->

div#mp3_player{ width:500px; height:10px; background:#000; padding:5px; margin:0px auto; position: fixed;
left: 0; bottom: 0; }
div#mp3_player > div > audio{  width:500px; background:#f8f8f8; float:left;  }
div#mp3_player > canvas{ width:500px; height:30px; background:#f8f8f8; float:left; }
div#mp3_player > div > solo{ width:500px; height:0px; background:#000000; float:left; }




</style>


<!-- add styles and scripts -->
    <%= javascript_include_tag :all %>
    <link href="css/styles.css" rel="stylesheet" type="text/css" />
    <%= javascript_include_tag 'inplayer', 'data-turbolinks-track' => true %>
    <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.8.21.custom.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>

    <%= stylesheet_link_tag "playerstyles", media: "all" %>
    <%= javascript_include_tag "sub/main", "jquery-1.7.2.min", "jquery-ui-1.8.21.custom.min" %>


</head>

<body>

  <div class="jumbotron centerfy">
  <h1>African Music Base</h1>
  <p>Free, easy and fun way to Share or promote African Music, Videos & Events..</p>
  
  <p><%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-lg" %> </p>
</div>
<br>







<!--div class="example">

        <div class="player">
            <div class="pl"></div>
            <div class="title"></div>
            <div class="artist"></div>
            <div class="cover"></div>
            <div class="controls">
                <div class="play"></div>
                <div class="pause"></div>
                <div class="rew"></div>
                <div class="fwd"></div>
            </div>
            <div class="volume"></div>
            <div class="tracker"></div>
        </div>
        @songs.each ddo |song| %>
              <ul class="playlist hidden">
                  <li audiourl="01.mp3" cover="cover1.jpg" artist="Artist 1">01.mp3</li>
                  <li audiourl="02.mp3" cover="cover2.jpg" artist="Artist 2">02.mp3</li>
                  <li audiourl="03.mp3" cover="cover3.jpg" artist="Artist 3">03.mp3</li>
                  <li audiourl="04.mp3" cover="cover4.jpg" artist="Artist 4">04.mp3</li>
                  <li audiourl="05.mp3" cover="cover5.jpg" artist="Artist 5">05.mp3</li>
                  <li audiourl="06.mp3" cover="cover6.jpg" artist="Artist 6">06.mp3</li>
                  <li audiourl="07.mp3" cover="cover7.jpg" artist="Artist 7">07.mp3</li>
              </ul>
        ennd 

    </div-->






<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">

          <div class="col-md-7">


            


            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover ">

              <% @songs.reverse_each do |song| %>


    
    <tr >
     
      <td>

        <% if song.cover? %>
                        
                        <%=link_to (image_tag song.cover.url(:front)), song %>

                      <% else %>
                        <%= image_tag("fallback/noimage.jpg") %>



                        
                        <% end %>


        </td>
      

      <td align="left">

        
              
          
       <div class="centerplayer">
        <button id="playpausebtn"></button>
        


</div>




          

 
          
          <!---<input type= "button" value= "Count" id= "countButton" />
          <p>yes<span id= "displayCount">0</span>plays. </p>
          <button type="button" class="btn btn-info btn-xs">23,779</button>-->              
        </td>
     
      <td class="" align="left" >     
       <%= link_to song.title, song %>
       </br>
       <%= song.artist %>
     </br>
     </br>
     <span class="glyphicon glyphicon-thumbs-up"></span>Like  <span class="glyphicon glyphicon-download-alt"></span>Download  <span class="glyphicon glyphicon-retweet"></span>Repost  <span class="glyphicon glyphicon-list"></span>
      </td>
        
        <td ><button type="button" class="btn btn-default btn-sm"> 
                                  <span class="glyphicon glyphicon-share btn btn-warning btn-xs"></span>
                            </button><span>24,755</span></td>


        

    </tr>
    <% end %>
    

  </table>
</div>

  
<!--script for individual player starts here-->


   <%= render 'player' %>     

 <!--script for analyzer starts here-->

<script>
// Create a new instance of an audio object and adjust some of its properties
var audio = new Audio();
audio.src = '';

audio.loop = true;
audio.autoplay = false;

// Establish all variables that your Analyser will use
var canvas, solo, ctx, source, context, analyser, fbc_array, bars, bar_x, bar_width, bar_height;
// Initialize the MP3 player after the page loads all of its HTML into the window
window.addEventListener("load", initMp3Player, false);
function initMp3Player(){
    document.getElementById('audio_box').appendChild(audio);
    context = new webkitAudioContext(); // AudioContext object instance
    solo = document.getElementById('solo_render');
    analyser = context.createAnalyser(); // AnalyserNode method
    canvas = document.getElementById('analyser_render');
    ctx = canvas.getContext('2d');
    // Re-route audio playback into the processing graph of the AudioContext
    source = context.createMediaElementSource(audio); 
    source.connect(analyser);
    analyser.connect(context.destination);
    frameLooper();
}
// frameLooper() animates any style of graphics you wish to the audio frequency
// Looping at the default frame rate that the browser provides(approx. 60 FPS)
function frameLooper(){
    window.webkitRequestAnimationFrame(frameLooper);
    fbc_array = new Uint8Array(analyser.frequencyBinCount);
    analyser.getByteFrequencyData(fbc_array);
    ctx.clearRect(0, 0, canvas.width, canvas.height); // Clear the canvas
    ctx.fillStyle = '#00CCFF'; // Color of the bars
    bars = 100;
    for (var i = 0; i < bars; i++) {
        bar_x = i * 3;
        bar_width = 2;
        bar_height = -(fbc_array[i] / 2);
        //fillRect( x, y, width, height ) // Explanation of the parameters below
        ctx.fillRect(bar_x, canvas.height, bar_width, bar_height);
    }
}
</script>


          


          <!--related feeds-->
          <div class="col-md-5"><%= image_tag "related.png" %></div>
        </div>
      <br>
          <% @songs.each do |song| %>
                <%= link_to 'New Song', new_song_path %>
                <%= link_to 'Edit', edit_song_path(song) %> |
                <%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %>|
                <%= link_to 'Back', songs_path %>


          <% end %>
      </div>
</div>






</body>



    <footer>
          <div class="player-wrap pindown centerfy">
            
<div class = "downanalyser" >

            <div id="mp3_player">
              
    <div id ="solo_render"></div>
    <div id="audio_box"></div>
  
  
  <canvas id="analyser_render"></canvas>

</div>
            
          </div> 

          </div>  
    </footer>

</html>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/users/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>



</head>

<body>



<p id="notice"><%= notice %></p>
<p></p>


<div class="em-background-box centerfy" style="background-image: url('')">


  
  <%= image_tag @user.avatar.url(:thumb) if @user.avatar? %>
  <p><%= @user.username %> | <%= @user.email %> </p>
  www.preachout.com/<%= @user.email %>

  

</div>




<p><%= link_to 'Edit', edit_user_path(current_user) %> </p>



      

</body>
</html>